import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import styles from '@/styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <script
        src="/script.js"/>
        <script src="/jquery.js"/>

        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  <div className="header">
    <div className="container">
      <div className="header-inner">
        <a href="/" className="logo-link w-inline-block">
          <img
            src="https://assets.website-files.com/6310ffd0c310a8603c82807d/63111282a9b5c23755faf4ed_logo.svg"
            loading="lazy"
            alt=""
            className="logo-img"
          />
        </a>
        <div className="header-nav">
          <a href="index.html" className="nav-link">
            home
          </a>
          <a href="index.html#work" className="nav-link">
            work
          </a>
          <a href="index.html#about" className="nav-link">
            about
          </a>
          <a
            href="blog.html"
            aria-current="page"
            className="nav-link w--current"
          >
            blog
          </a>
          <a href="index.html#contact" className="button large w-inline-block">
            <div className="button-inner large">
              <div className="text-micro-1 button-text text-color-light">
                contact
              </div>
            </div>
            <div className="button-bg" />
          </a>
        </div>
        <div className="nav-btn">
          <div
            data-is-ix2-target={1}
            className="nav-btn-icon"
            data-w-id="7ead97b8-ae39-c4ee-81c6-02f74d7da317"
            data-animation-type="lottie"
            data-src="https://assets.website-files.com/6310ffd0c310a8603c82807d/6310ffd0c310a85535828097_nav-lottie-ph.json"
            data-loop={0}
            data-direction={1}
            data-autoplay={0}
            data-renderer="svg"
            data-duration={0}
            data-ix2-initial-state={0}
          />
        </div>
      </div>
    </div>
  </div>
  <div style={{ opacity: 0 }} className="wrapper">
    <div className="section wf-section">
      <div className="container">
        <div className="row center">
          <div className="col">
            <h1 className="text-display-1">bravo</h1>
          </div>
          <div className="col margin-80">
            <h2 className="text-display-1">RESOURCES</h2>
          </div>
        </div>
        <div className="row blog">
          <div className="w-dyn-list">
            <div role="list" className="grid-thirds blog w-dyn-items">
              <div
                id="w-node-bece8a54-44bd-2aec-ff2e-5026fee5cc5f-6d828075"
                role="listitem"
                className="w-dyn-item"
              >
                <a
                  href="blog-posts/how-to-build-a-strong-branding.html"
                  className="blog-card w-inline-block"
                >
                  <div className="blog-card-top">
                    <div className="image-contain thumb margin-24">
                      <img
                        src="https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a825338280d7_61df396292340a457764a875_Blog%2520thumb%2520large%252004.jpeg"
                        loading="lazy"
                        alt=""
                        sizes="(max-width: 991px) 340px, 21vw"
                        srcSet="
                      https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a825338280d7_61df396292340a457764a875_Blog%252520thumb%252520large%25252004-p-500.jpeg   500w,
                      https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a825338280d7_61df396292340a457764a875_Blog%252520thumb%252520large%25252004-p-800.jpeg   800w,
                      https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a825338280d7_61df396292340a457764a875_Blog%252520thumb%252520large%25252004-p-1080.jpeg 1080w,
                      https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a825338280d7_61df396292340a457764a875_Blog%2520thumb%2520large%252004.jpeg              1280w
                    "
                        className="image"
                      />
                    </div>
                    <div className="margin-96">
                      <h2 className="text-display-5">
                        How to Build a Strong Personal Branding?
                      </h2>
                    </div>
                  </div>
                  <div className="blog-card-bottom">
                    <div className="text-micro-1 text-color-dark">
                      Ester Jones
                    </div>
                    <div className="text-micro-1 text-color-dark">
                      June 22, 2022
                    </div>
                  </div>
                </a>
              </div>
              <div
                id="w-node-bece8a54-44bd-2aec-ff2e-5026fee5cc5f-6d828075"
                role="listitem"
                className="w-dyn-item"
              >
                <a
                  href="blog-posts/what-is-the-duty-of-an-executive-producer.html"
                  className="blog-card w-inline-block"
                >
                  <div className="blog-card-top">
                    <div className="image-contain thumb margin-24">
                      <img
                        src="https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8472a8280d6_61df396292340a6dc264a86e_Blog%2520thumb%2520large%252007.jpeg"
                        loading="lazy"
                        alt=""
                        sizes="(max-width: 991px) 340px, 21vw"
                        srcSet="
                      https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8472a8280d6_61df396292340a6dc264a86e_Blog%252520thumb%252520large%25252007-p-500.jpeg   500w,
                      https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8472a8280d6_61df396292340a6dc264a86e_Blog%252520thumb%252520large%25252007-p-800.jpeg   800w,
                      https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8472a8280d6_61df396292340a6dc264a86e_Blog%252520thumb%252520large%25252007-p-1080.jpeg 1080w,
                      https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8472a8280d6_61df396292340a6dc264a86e_Blog%2520thumb%2520large%252007.jpeg              1280w
                    "
                        className="image"
                      />
                    </div>
                    <div className="margin-96">
                      <h2 className="text-display-5">
                        What is the duty of an Executive Producer?
                      </h2>
                    </div>
                  </div>
                  <div className="blog-card-bottom">
                    <div className="text-micro-1 text-color-dark">
                      Ester Jones
                    </div>
                    <div className="text-micro-1 text-color-dark">
                      June 22, 2022
                    </div>
                  </div>
                </a>
              </div>
              <div
                id="w-node-bece8a54-44bd-2aec-ff2e-5026fee5cc5f-6d828075"
                role="listitem"
                className="w-dyn-item"
              >
                <a
                  href="blog-posts/what-do-you-need-to-start-on-your-career.html"
                  className="blog-card w-inline-block"
                >
                  <div className="blog-card-top">
                    <div className="image-contain thumb margin-24">
                      <img
                        src="https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8dfbc8280d5_61df396292340a79d364a873_Blog%2520thumb%2520large%252005.jpeg"
                        loading="lazy"
                        alt=""
                        sizes="(max-width: 991px) 340px, 21vw"
                        srcSet="
                      https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8dfbc8280d5_61df396292340a79d364a873_Blog%252520thumb%252520large%25252005-p-500.jpeg   500w,
                      https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8dfbc8280d5_61df396292340a79d364a873_Blog%252520thumb%252520large%25252005-p-800.jpeg   800w,
                      https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8dfbc8280d5_61df396292340a79d364a873_Blog%252520thumb%252520large%25252005-p-1080.jpeg 1080w,
                      https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8dfbc8280d5_61df396292340a79d364a873_Blog%2520thumb%2520large%252005.jpeg              1280w
                    "
                        className="image"
                      />
                    </div>
                    <div className="margin-96">
                      <h2 className="text-display-5">
                        What Do You Need to Start on Your Career?
                      </h2>
                    </div>
                  </div>
                  <div className="blog-card-bottom">
                    <div className="text-micro-1 text-color-dark">
                      Ester Jones
                    </div>
                    <div className="text-micro-1 text-color-dark">
                      June 22, 2022
                    </div>
                  </div>
                </a>
              </div>
              <div
                id="w-node-bece8a54-44bd-2aec-ff2e-5026fee5cc5f-6d828075"
                role="listitem"
                className="w-dyn-item"
              >
                <a
                  href="blog-posts/the-role-of-a-creative-director-in-movies.html"
                  className="blog-card w-inline-block"
                >
                  <div className="blog-card-top">
                    <div className="image-contain thumb margin-24">
                      <img
                        src="https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a82c088280d1_61df396292340a6bb164a871_Blog%2520thumb%2520large%252006.jpeg"
                        loading="lazy"
                        alt=""
                        sizes="(max-width: 991px) 340px, 21vw"
                        srcSet="
                      https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a82c088280d1_61df396292340a6bb164a871_Blog%252520thumb%252520large%25252006-p-500.jpeg   500w,
                      https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a82c088280d1_61df396292340a6bb164a871_Blog%252520thumb%252520large%25252006-p-800.jpeg   800w,
                      https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a82c088280d1_61df396292340a6bb164a871_Blog%252520thumb%252520large%25252006-p-1080.jpeg 1080w,
                      https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a82c088280d1_61df396292340a6bb164a871_Blog%2520thumb%2520large%252006.jpeg              1280w
                    "
                        className="image"
                      />
                    </div>
                    <div className="margin-96">
                      <h2 className="text-display-5">
                        The Role of a Creative Director in movies
                      </h2>
                    </div>
                  </div>
                  <div className="blog-card-bottom">
                    <div className="text-micro-1 text-color-dark">
                      Ester Jones
                    </div>
                    <div className="text-micro-1 text-color-dark">
                      June 22, 2022
                    </div>
                  </div>
                </a>
              </div>
              <div
                id="w-node-bece8a54-44bd-2aec-ff2e-5026fee5cc5f-6d828075"
                role="listitem"
                className="w-dyn-item"
              >
                <a
                  href="blog-posts/the-complete-guide-to-help-you-with-film-editing.html"
                  className="blog-card w-inline-block"
                >
                  <div className="blog-card-top">
                    <div className="image-contain thumb margin-24">
                      <img
                        src="https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a88a378280d4_61df396292340ad56d64a87b_Blog%2520thumb%2520large%252001.jpeg"
                        loading="lazy"
                        alt=""
                        sizes="(max-width: 991px) 340px, 21vw"
                        srcSet="
                      https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a88a378280d4_61df396292340ad56d64a87b_Blog%252520thumb%252520large%25252001-p-500.jpeg   500w,
                      https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a88a378280d4_61df396292340ad56d64a87b_Blog%252520thumb%252520large%25252001-p-800.jpeg   800w,
                      https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a88a378280d4_61df396292340ad56d64a87b_Blog%252520thumb%252520large%25252001-p-1080.jpeg 1080w,
                      https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a88a378280d4_61df396292340ad56d64a87b_Blog%2520thumb%2520large%252001.jpeg              1280w
                    "
                        className="image"
                      />
                    </div>
                    <div className="margin-96">
                      <h2 className="text-display-5">
                        The Complete Guide to help you with Film Editing
                      </h2>
                    </div>
                  </div>
                  <div className="blog-card-bottom">
                    <div className="text-micro-1 text-color-dark">
                      Ester Jones
                    </div>
                    <div className="text-micro-1 text-color-dark">
                      June 22, 2022
                    </div>
                  </div>
                </a>
              </div>
              <div
                id="w-node-bece8a54-44bd-2aec-ff2e-5026fee5cc5f-6d828075"
                role="listitem"
                className="w-dyn-item"
              >
                <a
                  href="blog-posts/what-is-a-films-post-production-process.html"
                  className="blog-card w-inline-block"
                >
                  <div className="blog-card-top">
                    <div className="image-contain thumb margin-24">
                      <img
                        src="https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8dcde8280d2_61df396292340a193064a86d_Blog%2520thumb%2520large%252008.jpeg"
                        loading="lazy"
                        alt=""
                        sizes="(max-width: 991px) 340px, 21vw"
                        srcSet="
                      https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8dcde8280d2_61df396292340a193064a86d_Blog%252520thumb%252520large%25252008-p-500.jpeg   500w,
                      https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8dcde8280d2_61df396292340a193064a86d_Blog%252520thumb%252520large%25252008-p-800.jpeg   800w,
                      https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8dcde8280d2_61df396292340a193064a86d_Blog%252520thumb%252520large%25252008-p-1080.jpeg 1080w,
                      https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8dcde8280d2_61df396292340a193064a86d_Blog%2520thumb%2520large%252008.jpeg              1280w
                    "
                        className="image"
                      />
                    </div>
                    <div className="margin-96">
                      <h2 className="text-display-5">
                        What is a Film's Post-Production Process?
                      </h2>
                    </div>
                  </div>
                  <div className="blog-card-bottom">
                    <div className="text-micro-1 text-color-dark">
                      Ester Jones
                    </div>
                    <div className="text-micro-1 text-color-dark">
                      June 22, 2022
                    </div>
                  </div>
                </a>
              </div>
              <div
                id="w-node-bece8a54-44bd-2aec-ff2e-5026fee5cc5f-6d828075"
                role="listitem"
                className="w-dyn-item"
              >
                <a
                  href="blog-posts/learn-the-first-steps-of-becoming-a-film-editor.html"
                  className="blog-card w-inline-block"
                >
                  <div className="blog-card-top">
                    <div className="image-contain thumb margin-24">
                      <img
                        src="https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8f8708280d3_61df396292340aa8df64a877_Blog%2520thumb%2520large%252003.jpeg"
                        loading="lazy"
                        alt=""
                        sizes="(max-width: 991px) 340px, 21vw"
                        srcSet="
                      https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8f8708280d3_61df396292340aa8df64a877_Blog%252520thumb%252520large%25252003-p-500.jpeg   500w,
                      https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8f8708280d3_61df396292340aa8df64a877_Blog%252520thumb%252520large%25252003-p-800.jpeg   800w,
                      https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8f8708280d3_61df396292340aa8df64a877_Blog%252520thumb%252520large%25252003-p-1080.jpeg 1080w,
                      https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8f8708280d3_61df396292340aa8df64a877_Blog%2520thumb%2520large%252003.jpeg              1280w
                    "
                        className="image"
                      />
                    </div>
                    <div className="margin-96">
                      <h2 className="text-display-5">
                        Learn the First Steps of Becoming a Film Editor
                      </h2>
                    </div>
                  </div>
                  <div className="blog-card-bottom">
                    <div className="text-micro-1 text-color-dark">
                      Ester Jones
                    </div>
                    <div className="text-micro-1 text-color-dark">
                      June 22, 2022
                    </div>
                  </div>
                </a>
              </div>
              <div
                id="w-node-bece8a54-44bd-2aec-ff2e-5026fee5cc5f-6d828075"
                role="listitem"
                className="w-dyn-item"
              >
                <a
                  href="blog-posts/how-to-hire-a-film-editor-for-your-project.html"
                  className="blog-card w-inline-block"
                >
                  <div className="blog-card-top">
                    <div className="image-contain thumb margin-24">
                      <img
                        src="https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a860468280bc_61df396292340aa3f064a879_Blog%2520thumb%2520large%252002.jpeg"
                        loading="lazy"
                        alt=""
                        sizes="(max-width: 991px) 340px, 21vw"
                        srcSet="
                      https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a860468280bc_61df396292340aa3f064a879_Blog%252520thumb%252520large%25252002-p-500.jpeg   500w,
                      https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a860468280bc_61df396292340aa3f064a879_Blog%252520thumb%252520large%25252002-p-800.jpeg   800w,
                      https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a860468280bc_61df396292340aa3f064a879_Blog%252520thumb%252520large%25252002-p-1080.jpeg 1080w,
                      https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a860468280bc_61df396292340aa3f064a879_Blog%2520thumb%2520large%252002.jpeg              1280w
                    "
                        className="image"
                      />
                    </div>
                    <div className="margin-96">
                      <h2 className="text-display-5">
                        How to Hire a Film Editor for Your Project
                      </h2>
                    </div>
                  </div>
                  <div className="blog-card-bottom">
                    <div className="text-micro-1 text-color-dark">
                      Ester Jones
                    </div>
                    <div className="text-micro-1 text-color-dark">
                      June 22, 2022
                    </div>
                  </div>
                </a>
              </div>
              <div
                id="w-node-bece8a54-44bd-2aec-ff2e-5026fee5cc5f-6d828075"
                role="listitem"
                className="w-dyn-item"
              >
                <a
                  href="blog-posts/visual-design-basics-to-get-started-today.html"
                  className="blog-card w-inline-block"
                >
                  <div className="blog-card-top">
                    <div className="image-contain thumb margin-24">
                      <img
                        src="https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8d5e18280cd_61df396292340a701964a868_Blog%2520thumb%2520large%252009.jpeg"
                        loading="lazy"
                        alt=""
                        sizes="(max-width: 991px) 340px, 21vw"
                        srcSet="
                      https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8d5e18280cd_61df396292340a701964a868_Blog%252520thumb%252520large%25252009-p-500.jpeg   500w,
                      https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8d5e18280cd_61df396292340a701964a868_Blog%252520thumb%252520large%25252009-p-800.jpeg   800w,
                      https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8d5e18280cd_61df396292340a701964a868_Blog%252520thumb%252520large%25252009-p-1080.jpeg 1080w,
                      https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8d5e18280cd_61df396292340a701964a868_Blog%2520thumb%2520large%252009.jpeg              1280w
                    "
                        className="image"
                      />
                    </div>
                    <div className="margin-96">
                      <h2 className="text-display-5">
                        Visual Design Basics to get started today
                      </h2>
                    </div>
                  </div>
                  <div className="blog-card-bottom">
                    <div className="text-micro-1 text-color-dark">
                      Ester Jones
                    </div>
                    <div className="text-micro-1 text-color-dark">
                      June 22, 2022
                    </div>
                  </div>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <footer id="contact" className="section footer">
      <div className="container">
        <div className="row footer-wrap margin-120">
          <div className="col">
            <div className="margin-40">
              <h2>bravo®</h2>
            </div>
            <div className="footer-links">
              <a href="template/style-guide.html" className="text-link">
                STYLE GUIDE
              </a>
              <div className="text-divider">/</div>
              <a href="template/licenses.html" className="text-link">
                LICENSES
              </a>
              <div className="text-divider">/</div>
              <a href="template/changelog.html" className="text-link">
                CHANGELOG
              </a>
              <div className="text-divider">/</div>
              <a href="template/support.html" className="text-link">
                SUPPORT
              </a>
            </div>
          </div>
          <div className="contact">
            <div className="contact-top">
              <div className="margin-4">
                <div className="text-micro-1">contact</div>
              </div>
              <div className="text-micro-1 text-color-dark">
                9081 Lakewood <br />
                Gardens Junction
              </div>
            </div>
            <div className="line" />
            <div className="contact-bottom">
              <div className="margin-4">
                <div className="text-micro-1">contact</div>
              </div>
              <div className="social-wrap">
                <a href="template/style-guide.html" className="text-link">
                  TW
                </a>
                <a href="template/style-guide.html" className="text-link">
                  IG
                </a>
                <a href="template/style-guide.html" className="text-link">
                  FB
                </a>
                <a href="template/style-guide.html" className="text-link">
                  LN
                </a>
              </div>
            </div>
          </div>
        </div>
        <div className="row footer-bottom">
          <a
            href="https://www.webflow.com/"
            target="_blank"
            className="text-link"
          >
            POWERED BY WEBFLOW
          </a>
          <a
            href="http://www.leonardomattar.com/"
            target="_blank"
            className="text-link"
          >
            © LEONARDO MATTAR
          </a>
        </div>
      </div>
    </footer>
  </div>
    </>
  )
}
