import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Contact.module.css'

export default function Home() {
  return (
    <>
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div className="content">
  <div className="container">
    <div className="row justify-content-center">
      <div className="col-md-10">
        <div className="row justify-content-center">
          <div className="col-md-6">
            <h3 className="heading mb-4">Let's talk about everything!</h3>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptas
              debitis, fugit natus?
            </p>
            <p>
              <img
                src="images/undraw-contact.svg"
                alt="Image"
                className="img-fluid"
              />
            </p>
          </div>
          <div className="col-md-6">
            <form
              className="mb-5"
              method="post"
              id="contactForm"
              name="contactForm"
            >
              <div className="row">
                <div className="col-md-12 form-group">
                  <input
                    type="text"
                    className="form-control"
                    name="name"
                    id="name"
                    placeholder="Your name"
                  />
                </div>
              </div>
              <div className="row">
                <div className="col-md-12 form-group">
                  <input
                    type="text"
                    className="form-control"
                    name="email"
                    id="email"
                    placeholder="Email"
                  />
                </div>
              </div>
              <div className="row">
                <div className="col-md-12 form-group">
                  <input
                    type="text"
                    className="form-control"
                    name="subject"
                    id="subject"
                    placeholder="Subject"
                  />
                </div>
              </div>
              <div className="row">
                <div className="col-md-12 form-group">
                  <textarea
                    className="form-control"
                    name="message"
                    id="message"
                    cols={30}
                    rows={7}
                    placeholder="Write your message"
                    defaultValue={""}
                  />
                </div>
              </div>
              <div className="row">
                <div className="col-12">
                  <input
                    type="submit"
                    defaultValue="Send Message"
                    className="btn btn-primary rounded-0 py-2 px-4"
                  />
                  <span className="submitting" />
                </div>
              </div>
            </form>
            <div id="form-message-warning mt-4" />
            <div id="form-message-success">
              Your message was sent, thank you!
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
    </>
  )
}
