import Head from "next/head";
import Image from "next/image";
import Script from "next/script";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Shroud : An dedicated opensource developer. </title>
        <meta name="description" content="Generated by create next app" />
        <script src="/script.js" />
        <script src="/jquery.js" />

        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.webp" />
      </Head>
      <div className="header">
        <div className="container">
          <div className="header-inner">
            <a
              href="/"
              aria-current="page"
              className="logo-link w-inline-block w--current"
            >
              <img
                src="/logo.webp" height={50}
                loading="lazy"
                alt=""
                className="logo-img"
              />
            </a>
            <div className="header-nav">
              <a
                href="/"
                aria-current="page"
                className="nav-link button large w-inline-block"
              >
                home
              </a>
              <a href="/#work" className="nav-link button large w-inline-block">
                PROJECTS
              </a>
              <a
                href="/#about"
                className="nav-link button large w-inline-block"
              >
                about
              </a>
              <a href="/blog" className="nav-link button large w-inline-block">
                blog
              </a>
              <a
                href="/contact"
                className=" nav-link button large w-inline-block"
              >
                contact
              </a>
            </div>
            <div className="nav-btn">
              <div
                data-is-ix2-target={1}
                className="nav-btn-icon"
                data-w-id="7ead97b8-ae39-c4ee-81c6-02f74d7da317"
                data-animation-type="lottie"
                data-src="https://assets.website-files.com/6310ffd0c310a8603c82807d/6310ffd0c310a85535828097_nav-lottie-ph.json"
                data-loop={0}
                data-direction={1}
                data-autoplay={0}
                data-renderer="svg"
                data-duration={0}
                data-ix2-initial-state={0}
              />
            </div>
          </div>
        </div>
      </div>
      <div className="wrapper">
        <div className="section hero wf-section">
          <div className="container">
            <div className="row">
              <div className="col">
                <div className="text-mask">
                  <h1
                    data-w-id="25a6e989-41e9-a941-bc0d-321af5f8ee0a"
                    className="text-display-1"
                  >
                    creative
                  </h1>
                </div>
              </div>
              <div className="col">
                <div className="text-mask">
                  <h2
                    data-w-id="aea77a67-3188-a9ee-482d-d2d917c199bf"
                    className="text-display-1"
                  >
                    developer
                  </h2>
                </div>
              </div>
            </div>
            <div className="row hero-image">
              <div
                data-w-id="46f161e5-c6be-f0b5-7932-08117de03722"
                className="image-contain hero"
              >
                <img
                  src="/home-hero.webp"
                  loading="lazy"
                  alt=""
                  className="image"
                />
              </div>
            </div>
          </div>
        </div>
        <div id="work" className="section padding-bottom-0 wf-section">
          <div className="container">
            <div className="row work-card-wrap">
              <div className="work-card card-1">
                <div className="work-left">
                  <div className="work-top">
                    <div className="work-category margin-40">
                      <div
                        style={{ opacity: 0 }}
                        className="work-category-icon"
                      />
                      <div className="text-micro-1">
                        <i>OSS - Open Source</i>
                      </div>
                    </div>
                    <div className="margin-40">
                      <h2 className="text-display-3">Open-source</h2>
                    </div>
                    <div className="col _10-24 text-xl">
                      <p className="text-body-2 text-color-dark">
                        See how I develop and contribute to open-source
                        software. Making open-source the core of many
                        proprietary softwares.
                      </p>
                    </div>
                  </div>
                  <div className="work-bottom">
                    <a
                      data-w-id="f8064677-54b7-4603-9a8a-2f22c5686aca"
                      href="https://shroud.dee.al"
                      target="_blank"
                      className="button w-inline-block"
                    >
                      <div className="button-inner">
                        <div className="text-micro-1 button-text">
                          <strong>view PROJECTS</strong>
                        </div>
                        <img
                          src="./redirect.svg"
                          loading="lazy"
                          alt=""
                          className="button-icon"
                        />
                      </div>
                      <div className="button-bg" />
                    </a>
                  </div>
                </div>
                <div className="work-right">
                  <div className="image-contain work">
                    <img
                      src="/opensource.webp"
                      loading="lazy"
                      alt=""
                      className="image"
                    />
                  </div>
                </div>
              </div>
              <div className="work-card card-2">
                <div className="work-left">
                  <div className="work-top">
                    <div className="work-category margin-40">
                      <div
                        style={{ opacity: 0 }}
                        className="work-category-icon"
                      />
                      <div className="text-micro-1">
                        <i>POSS - proprietary opensource software</i>
                      </div>
                    </div>
                    <div className="margin-40">
                      <h2 className="text-display-4">
                        Proprietary Open Source
                      </h2>
                    </div>
                    <div className="col _10-24 text-xl">
                      <p className="text-body-2 text-color-dark">
                        See how I create proprietary software using the power of
                        open-source, Making software user-friendly and privacy
                        focused.
                      </p>
                    </div>
                  </div>
                  <div className="work-bottom">
                    <a
                      href="https://www.webflow.com/"
                      target="_blank"
                      className="button w-inline-block"
                    >
                      <div className="button-inner">
                        <div className="text-micro-1 button-text">
                          <strong>view PROJECTS</strong>
                        </div>
                        <img
                          src="./redirect.svg"
                          loading="lazy"
                          alt=""
                          className="button-icon"
                        />
                      </div>
                      <div className="button-bg" />
                    </a>
                  </div>
                </div>
                <div className="work-right">
                  <div className="image-contain work">
                    <img
                      src="/software.webp"
                      loading="lazy"
                      alt=""
                      className="image"
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div id="about" className="section padding-bottom-0 wf-section">
          <div className="container">
            <div className="row about">
              <div className="col _6-24">
                <div className="image-contain about">
                  <img
                    src="https://assets.website-files.com/6310ffd0c310a8603c82807d/6314ef4764bb4ef270a27f39_about-img.webp"
                    loading="lazy"
                    srcSet="/about-hero.webp"
                    alt=""
                    className="image"
                  />
                </div>
              </div>
              <div className="col _15-24">
                <div className="margin-64">
                  <h2 className="text-display-4">
                    An dedicated open-source developer
                  </h2>
                </div>
                <div className="about-item">
                  <h3 className="text-display-5">01</h3>
                  <p className="text-body-1 text-color-dark">
                    Finding a software that lacks user-experience, privacy or
                    speed. Dedictated to develop software with user experience
                    with cutting-edge speed.
                  </p>
                </div>
                <div className="about-item">
                  <h3 className="text-display-5">02</h3>
                  <p className="text-body-1 text-color-dark">
                    Reimagining software to provide privacy, user-experience. Dedicated to create software with unparallel execution velocity with privacy in mind.
                  </p>
                </div>
                <div className="about-item last">
                  <h3 className="text-display-5">03</h3>
                  <p className="text-body-1 text-color-dark">
                    Shipping software through a dedicated release system. Shipping software with an optimized and efficient release system for faster shipping. 
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="section blog wf-section">
          <div className="container">
            <div className="row title-header margin-80">
              <div className="col _10-24">
                <h2 className="text-display-3">Blog resources</h2>
              </div>
              <a href="blog.html" className="button w-inline-block">
                <div className="button-inner">
                  <div className="text-micro-1 button-text">view all posts</div>
                  <img
                    src="./redirect.svg"
                    loading="lazy"
                    alt=""
                    className="button-icon"
                  />
                </div>
                <div className="button-bg" />
              </a>
            </div>
            <div className="row margin-56">
              <div
                data-delay={4000}
                data-animation="slide"
                className="slider w-slider"
                data-autoplay="false"
                data-easing="ease"
                data-hide-arrows="false"
                data-disable-swipe="false"
                data-autoplay-limit={0}
                data-nav-spacing={3}
                data-duration={500}
                data-infinite="false"
              >
                <div className="slider-mask w-slider-mask">
                  <div className="slide w-slide">
                    <div className="w-dyn-list">
                      <div role="list" className="w-dyn-items">
                        <div role="listitem" className="w-dyn-item">
                          <a
                            href="blog-posts/how-to-build-a-strong-branding.html"
                            className="blog-card w-inline-block"
                          >
                            <div className="blog-card-top">
                              <div className="image-contain thumb margin-24">
                                <img
                                  src="https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a825338280d7_61df396292340a457764a875_Blog%2520thumb%2520large%252004.jpeg"
                                  loading="lazy"
                                  alt=""
                                  sizes="(max-width: 991px) 340px, 21vw"
                                  srcSet="
                            https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a825338280d7_61df396292340a457764a875_Blog%252520thumb%252520large%25252004-p-500.jpeg   500w,
                            https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a825338280d7_61df396292340a457764a875_Blog%252520thumb%252520large%25252004-p-800.jpeg   800w,
                            https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a825338280d7_61df396292340a457764a875_Blog%252520thumb%252520large%25252004-p-1080.jpeg 1080w,
                            https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a825338280d7_61df396292340a457764a875_Blog%2520thumb%2520large%252004.jpeg              1280w
                          "
                                  className="image"
                                />
                              </div>
                              <div className="margin-96">
                                <h1 className="text-display-5">
                                  How to Build a Strong Personal Branding?
                                </h1>
                              </div>
                            </div>
                            <div className="blog-card-bottom">
                              <div className="text-micro-1 text-color-dark">
                                Shroud
                              </div>
                              <div className="text-micro-1 text-color-dark">
                                Jun 22
                              </div>
                            </div>
                          </a>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="slide w-slide">
                    <div className="w-dyn-list">
                      <div role="list" className="w-dyn-items">
                        <div role="listitem" className="w-dyn-item">
                          <a
                            href="blog-posts/what-is-the-duty-of-an-executive-producer.html"
                            className="blog-card w-inline-block"
                          >
                            <div className="image-contain thumb margin-24">
                              <img
                                src="https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8472a8280d6_61df396292340a6dc264a86e_Blog%2520thumb%2520large%252007.jpeg"
                                loading="lazy"
                                alt=""
                                sizes="(max-width: 991px) 340px, 21vw"
                                srcSet="
                          https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8472a8280d6_61df396292340a6dc264a86e_Blog%252520thumb%252520large%25252007-p-500.jpeg   500w,
                          https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8472a8280d6_61df396292340a6dc264a86e_Blog%252520thumb%252520large%25252007-p-800.jpeg   800w,
                          https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8472a8280d6_61df396292340a6dc264a86e_Blog%252520thumb%252520large%25252007-p-1080.jpeg 1080w,
                          https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8472a8280d6_61df396292340a6dc264a86e_Blog%2520thumb%2520large%252007.jpeg              1280w
                        "
                                className="image"
                              />
                            </div>
                            <div className="margin-96">
                              <h1 className="text-display-5">
                                What is the duty of an Executive Producer?
                              </h1>
                            </div>
                            <div className="blog-card-bottom">
                              <div className="text-micro-1 text-color-dark">
                                Shroud
                              </div>
                              <div className="text-micro-1 text-color-dark">
                                Jun 22
                              </div>
                            </div>
                          </a>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="slide w-slide">
                    <div className="w-dyn-list">
                      <div role="list" className="w-dyn-items">
                        <div role="listitem" className="w-dyn-item">
                          <a
                            href="blog-posts/what-do-you-need-to-start-on-your-career.html"
                            className="blog-card w-inline-block"
                          >
                            <div className="image-contain thumb margin-24">
                              <img
                                src="https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8dfbc8280d5_61df396292340a79d364a873_Blog%2520thumb%2520large%252005.jpeg"
                                loading="lazy"
                                alt=""
                                sizes="(max-width: 991px) 340px, 21vw"
                                srcSet="
                          https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8dfbc8280d5_61df396292340a79d364a873_Blog%252520thumb%252520large%25252005-p-500.jpeg   500w,
                          https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8dfbc8280d5_61df396292340a79d364a873_Blog%252520thumb%252520large%25252005-p-800.jpeg   800w,
                          https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8dfbc8280d5_61df396292340a79d364a873_Blog%252520thumb%252520large%25252005-p-1080.jpeg 1080w,
                          https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8dfbc8280d5_61df396292340a79d364a873_Blog%2520thumb%2520large%252005.jpeg              1280w
                        "
                                className="image"
                              />
                            </div>
                            <div className="margin-96">
                              <h1 className="text-display-5">
                                What Do You Need to Start on Your Career?
                              </h1>
                            </div>
                            <div className="blog-card-bottom">
                              <div className="text-micro-1 text-color-dark">
                                Shroud
                              </div>
                              <div className="text-micro-1 text-color-dark">
                                Jun 22
                              </div>
                            </div>
                          </a>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="slide w-slide">
                    <div className="w-dyn-list">
                      <div role="list" className="w-dyn-items">
                        <div role="listitem" className="w-dyn-item">
                          <a
                            href="blog-posts/the-role-of-a-creative-director-in-movies.html"
                            className="blog-card w-inline-block"
                          >
                            <div className="image-contain thumb margin-24">
                              <img
                                src="https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a82c088280d1_61df396292340a6bb164a871_Blog%2520thumb%2520large%252006.jpeg"
                                loading="lazy"
                                alt=""
                                sizes="(max-width: 991px) 340px, 21vw"
                                srcSet="
                          https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a82c088280d1_61df396292340a6bb164a871_Blog%252520thumb%252520large%25252006-p-500.jpeg   500w,
                          https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a82c088280d1_61df396292340a6bb164a871_Blog%252520thumb%252520large%25252006-p-800.jpeg   800w,
                          https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a82c088280d1_61df396292340a6bb164a871_Blog%252520thumb%252520large%25252006-p-1080.jpeg 1080w,
                          https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a82c088280d1_61df396292340a6bb164a871_Blog%2520thumb%2520large%252006.jpeg              1280w
                        "
                                className="image"
                              />
                            </div>
                            <div className="margin-96">
                              <h1 className="text-display-5">
                                The Role of a Creative Director in movies
                              </h1>
                            </div>
                            <div className="blog-card-bottom">
                              <div className="text-micro-1 text-color-dark">
                                Shroud
                              </div>
                              <div className="text-micro-1 text-color-dark">
                                Jun 22
                              </div>
                            </div>
                          </a>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="slide w-slide">
                    <div className="w-dyn-list">
                      <div role="list" className="w-dyn-items">
                        <div role="listitem" className="w-dyn-item">
                          <a
                            href="blog-posts/the-complete-guide-to-help-you-with-film-editing.html"
                            className="blog-card w-inline-block"
                          >
                            <div className="image-contain thumb margin-24">
                              <img
                                src="https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a88a378280d4_61df396292340ad56d64a87b_Blog%2520thumb%2520large%252001.jpeg"
                                loading="lazy"
                                alt=""
                                sizes="(max-width: 991px) 340px, 21vw"
                                srcSet="
                          https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a88a378280d4_61df396292340ad56d64a87b_Blog%252520thumb%252520large%25252001-p-500.jpeg   500w,
                          https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a88a378280d4_61df396292340ad56d64a87b_Blog%252520thumb%252520large%25252001-p-800.jpeg   800w,
                          https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a88a378280d4_61df396292340ad56d64a87b_Blog%252520thumb%252520large%25252001-p-1080.jpeg 1080w,
                          https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a88a378280d4_61df396292340ad56d64a87b_Blog%2520thumb%2520large%252001.jpeg              1280w
                        "
                                className="image"
                              />
                            </div>
                            <div className="margin-96">
                              <h1 className="text-display-5">
                                The Complete Guide to help you with Film Editing
                              </h1>
                            </div>
                            <div className="blog-card-bottom">
                              <div className="text-micro-1 text-color-dark">
                                Shroud
                              </div>
                              <div className="text-micro-1 text-color-dark">
                                Jun 22
                              </div>
                            </div>
                          </a>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="slide w-slide">
                    <div className="w-dyn-list">
                      <div role="list" className="w-dyn-items">
                        <div role="listitem" className="w-dyn-item">
                          <a
                            href="blog-posts/what-is-a-films-post-production-process.html"
                            className="blog-card w-inline-block"
                          >
                            <div className="image-contain thumb margin-24">
                              <img
                                src="https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8dcde8280d2_61df396292340a193064a86d_Blog%2520thumb%2520large%252008.jpeg"
                                loading="lazy"
                                alt=""
                                sizes="(max-width: 991px) 340px, 21vw"
                                srcSet="
                          https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8dcde8280d2_61df396292340a193064a86d_Blog%252520thumb%252520large%25252008-p-500.jpeg   500w,
                          https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8dcde8280d2_61df396292340a193064a86d_Blog%252520thumb%252520large%25252008-p-800.jpeg   800w,
                          https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8dcde8280d2_61df396292340a193064a86d_Blog%252520thumb%252520large%25252008-p-1080.jpeg 1080w,
                          https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8dcde8280d2_61df396292340a193064a86d_Blog%2520thumb%2520large%252008.jpeg              1280w
                        "
                                className="image"
                              />
                            </div>
                            <div className="margin-96">
                              <h1 className="text-display-5">
                                What is a Film's Post-Production Process?
                              </h1>
                            </div>
                            <div className="blog-card-bottom">
                              <div className="text-micro-1 text-color-dark">
                                Shroud
                              </div>
                              <div className="text-micro-1 text-color-dark">
                                Jun 22
                              </div>
                            </div>
                          </a>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="slide w-slide">
                    <div className="w-dyn-list">
                      <div role="list" className="w-dyn-items">
                        <div role="listitem" className="w-dyn-item">
                          <a
                            href="blog-posts/learn-the-first-steps-of-becoming-a-film-editor.html"
                            className="blog-card w-inline-block"
                          >
                            <div className="image-contain thumb margin-24">
                              <img
                                src="https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8f8708280d3_61df396292340aa8df64a877_Blog%2520thumb%2520large%252003.jpeg"
                                loading="lazy"
                                alt=""
                                sizes="(max-width: 991px) 340px, 21vw"
                                srcSet="
                          https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8f8708280d3_61df396292340aa8df64a877_Blog%252520thumb%252520large%25252003-p-500.jpeg   500w,
                          https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8f8708280d3_61df396292340aa8df64a877_Blog%252520thumb%252520large%25252003-p-800.jpeg   800w,
                          https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8f8708280d3_61df396292340aa8df64a877_Blog%252520thumb%252520large%25252003-p-1080.jpeg 1080w,
                          https://assets.website-files.com/6310ffd0c310a89e728280a4/6310ffd0c310a8f8708280d3_61df396292340aa8df64a877_Blog%2520thumb%2520large%252003.jpeg              1280w
                        "
                                className="image"
                              />
                            </div>
                            <div className="margin-96">
                              <h1 className="text-display-5">
                                Learn the First Steps of Becoming a Film Editor
                              </h1>
                            </div>
                            <div className="blog-card-bottom">
                              <div className="text-micro-1 text-color-dark">
                                Shroud
                              </div>
                              <div className="text-micro-1 text-color-dark">
                                Jun 22
                              </div>
                            </div>
                          </a>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="slider-left-arrow w-slider-arrow-left">
                  <img
                    src="https://assets.website-files.com/6310ffd0c310a8603c82807d/63111282a37cd03dd8ddafd6_slider-lt-icon.svg"
                    loading="lazy"
                    alt=""
                    className="left-arrow-icon"
                  />
                </div>
                <div className="slider-right-arrow w-slider-arrow-right">
                  <img
                    src="https://assets.website-files.com/6310ffd0c310a8603c82807d/63111282e503e3b53f117c2f_slider-rt-icon.svg"
                    loading="lazy"
                    alt=""
                    className="right-arrow-icon"
                  />
                </div>
                <div className="slider-nav w-slider-nav w-round" />
              </div>
            </div>
          </div>
        </div>
        <footer id="contact" className="section footer">
          <div className="container">
            <div className="row footer-wrap margin-120">
              <div className="col">
                <div className="margin-40">
                  <h2>5HR0UD®</h2>
                </div>
                <div className="footer-links">
                  <a href="template/style-guide.html" className="text-link">
                    STYLE GUIDE
                  </a>
                  <div className="text-divider">/</div>
                  <a href="template/licenses.html" className="text-link">
                    LICENSES
                  </a>
                  <div className="text-divider">/</div>
                  <a href="template/changelog.html" className="text-link">
                    CHANGELOG
                  </a>
                  <div className="text-divider">/</div>
                  <a href="template/support.html" className="text-link">
                    SUPPORT
                  </a>
                </div>
              </div>
              <div className="contact">
                <div className="contact-top">
                  <div className="margin-4">
                    <div className="text-micro-1">contact</div>
                  </div>
                  <div className="text-micro-1 text-color-dark">
                    <a className="email-link" href="mailto:contact@shroud.localplayer.dev">contact@shroud.localplayer.dev</a>
                  </div>
                </div>
                <div className="line" />
                <div className="contact-bottom">
                  <div className="margin-4">
                    <div className="text-micro-1">contact</div>
                  </div>
                  <div className="social-wrap">
                    <a href="https://gitlab.com/SHR0UD" className="text-link">
                      <img src="./gitlab.svg" alt="gitlab" />
                    </a>
                    <a href="https://dev.to/shroud" className="text-link">
                      <img src="./devto.svg" alt="dev.to" />
                    </a>
                  </div>
                </div>
              </div>
            </div>
            <div className="row footer-bottom">
              <a
                href="http://shroud.dee.al/"
                target="_blank"
                className="text-link"
              >
                COPYRIGHT © SHROUD
              </a>
            </div>
          </div>
        </footer>
      </div>
    </>
  );
}
